#!/bin/bash

echo This script will install postgresql. DO you want to continue?

echo type yes or no

read answer

if  [[ $answer == 'yes' ]] ; then
        echo "installing...."


sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
sudo apt-get update
sudo apt-get -y install postgresql

echo to start Postgresql server locally run  sudo systemctl start postgresql@13-main
else
	exit 0

fi

exit 0
