#!/bin/bash

# 
# Usage: ./sanardidir

echo "Which directory would you like to activate?"

read DIR

# sudo find / -name $DIR -type d

cd $DIR
pwd
ls

# kill $(ps aux | grep $TOKILL | grep -v grep | awk '{ print$2 }' ) 

echo 'Here your requested directory'

exit 0
